# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [ ]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [46]:
#todo: 
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [49]:
#todo:
array_zeros = np.zeros((1, 5), int)
print(array_zeros)

array_zeros[0][2] = 5
print(array_zeros)

[[0 0 0 0 0]]
[[0 0 5 0 0]]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [74]:
#todo: 
rng = np.random.default_rng() # Generador de números aleatorios
matriz = rng.integers(0, 2, size=(3, 3)) # Genera una matriz de 3x3 con números aleatorios entre 0 y 2(no incluido)

print(matriz)

[[1 1 0]
 [1 1 1]
 [1 1 1]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:
arr = np.array([10, 20, 30, 40, 50])
print(f'Arreglo original: {arr}')

arr += 5
print(f'Arreglo después de sumar 5: {arr}')

num = randint(1, 10)
arr *= num
print(f'Arreglo después de multiplicar por {num}: {arr}')


Arreglo original: [10 20 30 40 50]
Arreglo después de sumar 5: [15 25 35 45 55]
Arreglo después de multiplicar por 8: [120 200 280 360 440]
[120 200 280 360 440]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
matriz = np.eye(4, 4)

print(f'Matriz identidad de 3x1:\n{matriz}')

Matriz identidad de 3x1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 
array = np.arange(0, 21, 1)
print(f'Arreglo original: {array}')

array_pair = array[2::2]
print(f'Arreglo con elementos pares: {array_pair}')

sum_array = np.add(array_pair, 2)
print(f'Suma de elementos: {sum_array}')

sub_array = np.subtract(array_pair, 2)
print(f'Resta de elementos: {sub_array}')

multi_array = np.multiply(array_pair, 2)
print(f'Multiplicación de elementos: {multi_array}')

divi_array = np.divide(array_pair, 2)
print(f'División de elementos: {divi_array}')




Arreglo original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Arreglo con elementos pares: [ 2  4  6  8 10 12 14 16 18 20]
Suma de elementos: [ 4  6  8 10 12 14 16 18 20 22]
Resta de elementos: [ 0  2  4  6  8 10 12 14 16 18]
Multiplicación de elementos: [ 4  8 12 16 20 24 28 32 36 40]


TypeError: No loop matching the specified signature and casting was found for ufunc divide